### PR TITLE
fix runtime config reconcile

### LINKED ISSUE #149: Manually scaling the deployment replicas
```
$ kubectl get spinapps
NAME       READY   DESIRED   EXECUTOR
bug-bash   2       2         containerd-shim-spin
$ kubectl scale deployment bug-bash --replicas 100
$ kubectl get spinapps
NAME       READY   DESIRED   EXECUTOR
bug-bash   100     2         containerd-shim-spin
```

### PR DESCRIPTION
**Pull request by rajatjindal**
fixes #149

### CODE REVIEW

File: internal/controller/spinapp_controller_test.go [hunk 1]
```diff
@@ -286,6 +286,119 @@ url = 'redis://localhost:9000'
...
+	expected := `[[config_provider]]
+type = 'env'
+prefix = 'SPIN_VARIABLE_'
+
+[key_value_store]
+[key_value_store.default]
+type = 'redis'
+url = 'redis://localhost:9000'
+`
+	require.Equal(t, expected, string(rcSecret.Data["runtime-config.toml"]))
```
Comment (endocrimes) [inline internal/controller/spinapp_controller_test.go:381]:
```suggestion
```

File: internal/controller/spinapp_controller_test.go [hunk 2]
```diff
@@ -304,7 +304,7 @@ func TestReconcile_Integration_RuntimeConfig_SecretAlreadyExists(t *testing.T) {
 	// Create an executor that creates a deployment with a given runtimeClassName
 	executor := &spinv1alpha1.SpinAppExecutor{
 		ObjectMeta: metav1.ObjectMeta{
-			Name:      "executor",
+			Name:      "foo-executor",
```
Comment (endocrimes) [inline internal/controller/spinapp_controller_test.go:307]: tests run with completely clean state, so the `foo-` prefixing shouldn't be necessary

File: internal/controller/spinapp_controller.go [hunk 3]
```diff
@@ -264,13 +264,13 @@ func (r *SpinAppReconciler) reconcileDeployment(ctx context.Context, app *spinv1
...
-			if client.IgnoreAlreadyExists(err) == nil {
-				log.Debug("RuntimeConfig Secret already exists", "runtime_config_secret_name", secret.ObjectMeta.Name)
+			if client.IgnoreAlreadyExists(err) != nil {
+				return fmt.Errorf("failed to create RuntimeConfig secret: %w", err)
 			}
-			return fmt.Errorf("failed to create RuntimeConfig secret: %w", err)
+			log.Debug("RuntimeConfig Secret already exists", "runtime_config_secret_name", secret.ObjectMeta.Name)
+		} else {
+			log.Info("created runtimeconfig secret")
 		}
```
Comment (endocrimes) [inline internal/controller/spinapp_controller.go:273]:
```suggestion
		}
```

we can drop this log

**Review by endocrimes — APPROVED** [review]

**Comment by endocrimes** [comment]
needs a rebase then this can land
